/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pipifax_gpio_GpioNative */

#ifndef _Included_org_pipifax_gpio_GpioNative
#define _Included_org_pipifax_gpio_GpioNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pipifax_gpio_GpioNative
 * Method:    initPinMap
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_pipifax_gpio_GpioNative_initPinMap
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_pipifax_gpio_GpioNative
 * Method:    init
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pipifax_gpio_GpioNative_init
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_pipifax_gpio_GpioNative
 * Method:    enableOutput
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_pipifax_gpio_GpioNative_enableOutput
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_pipifax_gpio_GpioNative
 * Method:    writeDigital
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_pipifax_gpio_GpioNative_writeDigital
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_pipifax_gpio_GpioNative
 * Method:    createProgram
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_org_pipifax_gpio_GpioNative_createProgram
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_pipifax_gpio_GpioNative
 * Method:    setProgram
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_org_pipifax_gpio_GpioNative_setProgram
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     org_pipifax_gpio_GpioNative
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_pipifax_gpio_GpioNative_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
